import React from 'react';
import {RxState} from '../../stores/util';
import auth from '../../stores/auth';

const wikiUris = {
    pipelines: 'https://github.com/Exynize/exynize-platform/wiki/Pipelines',
    components: 'https://github.com/Exynize/exynize-platform/wiki/Components:-General-concepts',
    sources: 'https://github.com/Exynize/exynize-platform/wiki/Components:-Source',
    processors: 'https://github.com/Exynize/exynize-platform/wiki/Components:-Processor',
    renders: 'https://github.com/Exynize/exynize-platform/wiki/Components:-Render',
    architecture: 'https://github.com/Exynize/exynize-platform/wiki/Architecture-overview',
    helloworld: 'https://github.com/Exynize/exynize-platform/wiki/Tutorial:-Hello-world',
    twitter: 'https://github.com/Exynize/exynize-platform/wiki/Tutorial:-Twitter-product-comparison',
    bbc: 'https://github.com/Exynize/exynize-platform/wiki/Tutorial:-BBC-world-news-map',
    slackbot: 'https://github.com/Exynize/exynize-platform/wiki/Tutorial:-Slack-slash-command',
    slackslash: 'https://github.com/Exynize/exynize-platform/wiki/Tutorial:-Slack-bot',
};

const Home = React.createClass({
    mixins: [RxState],
    stores: {
        authed: auth.map(v => v.get('authed')),
    },

    render() {
        return (
            <div className="row">
                <div className="col-xs-6 col-xs-offset-3">
                    <h3>What is Exynize?</h3>
                    <blockquote>
                        <strong className="text-danger">Alpha</strong>
                        <p>
                            This is an Alpha release of Exynize platform.
                            Features might be changed in backward-incompatible ways, things might break
                            and it is not recommended for production use.
                        </p>
                    </blockquote>
                    <p className="description-text">
                        Exynize is a lightweight asynchronous compute solution
                        that allows you to create small, single-purpose functions (and pipelines from those functions)
                        that respond to cloud events without the need to manage a server or a runtime environment.
                    </p>
                    <p className="description-text">
                        <a href={wikiUris.helloworld}>Start by trying "Hello world" tutorial.</a>
                    </p>
                    <p className="description-text">
                        Exynize is written in Javascript and execute in a managed Node.js environment.
                        Exynize provides three different types of functions (also refered to as "components"):
                    </p>
                    <ul className="description-text">
                        <li>
                            <strong>
                                <a href={wikiUris.sources}>Source components</a>
                            </strong> - generate events and/or data that should be processed.
                        </li>
                        <li>
                            <strong>
                                <a href={wikiUris.processors}>Processor components</a>
                            </strong> - processes the incoming data, can be either plugged into
                                source or chained after another processor.
                        </li>
                        <li>
                            <strong>
                                <a href={wikiUris.renders}>Render components</a>
                            </strong> - renders the final result as HTML.
                        </li>
                    </ul>
                    <p className="description-text">
                        All components are executed as stand-alone microservices and can do processing in real-time
                        as more events/data comes in.
                        You can find out more on how components work in a <a href={wikiUris.components}>Components</a>
                        &nbsp;wiki page.
                        Those components can be combined into more complex processing functions called "pipelines".
                        Pipeline always includes one source, at least one processor and one renderer.
                        You can find out more on how pipelines work in a <a href={wikiUris.pipelines}>Pipelines</a>
                        &nbsp;wiki page.
                    </p>
                    <p className="description-text">
                        <a href={wikiUris.architecture}>Read more about Exynize architecture.</a>
                    </p>
                    <h3>Sources</h3>
                    <p className="description-text">
                        Sources are functions generating events and/or data that should be processed.
                        Events generated by sources will trigger processors asynchronously.
                        It is also possible to use HTTP requests and WebSocket to pass additional data to sources
                        that are already running.
                    </p>
                    <p className="description-text">
                        <a href={wikiUris.sources}>Read more about sources.</a>
                    </p>
                    <h3>Processors</h3>
                    <p className="description-text">
                        Processors are functions processing the incoming events and/or data.
                        Processors can be both - synchronous and asynchronous.
                        It is also possible to use processors to produce side-effects
                        (e.g. send emails, send slack message, etc).
                    </p>
                    <p className="description-text">
                        <a href={wikiUris.processors}>Read more about processors.</a>
                    </p>
                    <h3>Renders</h3>
                    <p className="description-text">
                        Renders are the functions used for rendering the results of the pipeline.
                        Renders create a React component that should handle the results.
                        The data will be delivered to renders in real-time as it comes through the pipeline.
                    </p>
                    <p className="description-text">
                        <a href={wikiUris.renders}>Read more about renderers.</a>
                    </p>
                    <h3>Additional info</h3>
                    <p className="description-text">
                        You can additionally read the following tutorials:
                    </p>
                    <ul className="description-text">
                        <li><a href={wikiUris.helloworld}>Hello world tutorial</a></li>
                        <li><a href={wikiUris.twitter}>Twitter product comparison tutorial</a></li>
                        <li><a href={wikiUris.bbc}>BBC world news sentiments map tutorial</a></li>
                        <li><a href={wikiUris.slackslash}>Slack slash command tutorial</a></li>
                        <li><a href={wikiUris.slackbot}>Slack search bot tutorial</a></li>
                    </ul>
                </div>
            </div>
        );
    },
});

export default Home;
